/* eslint-disable sonarjs/redundant-type-aliases -- `ChatStreamServerMessage`
   aliases `string` deliberately: naming the wire frame makes call sites read as
   protocol code, and gives the type somewhere to live if the backend ever moves
   to structured frames. */

/**
 * Generated by `backend/schemas/typescript.py` -- DO NOT EDIT BY HAND.
 *
 * The Pydantic models under `backend/schemas/` are the single source of truth
 * for every payload crossing the frontend/backend boundary. Regenerate with:
 *
 *     make generate_api_types
 *
 * `tests/api/test_api_contract.py` fails the build when this file is stale.
 */

/** Body of `POST /chat/`, and the client -> server frame of `WS /chat/stream`. */
export interface ChatRequest {
  text: string;
  rag?: boolean;
  reasoning?: boolean;
  web_search?: boolean;
}

/** One entry in the `GET /documents` listing. */
export interface DocumentInfo {
  document_id: string;
  filename: string;
  size: number;
  content_type: string;
  version_hash: string;
}

/** Response of `POST /documents`. */
export interface DocumentUploadResponse {
  document_id: string;
  filename: string;
}

/** Response of `GET /documents`. */
export interface DocumentListResponse {
  documents: DocumentInfo[];
}

/** Response of `GET /health`. */
export interface HealthResponse {
  status: string;
  version: string;
}

/**
 * Client -> server frame on `WS /chat/stream`.
 *
 * The endpoint reads each frame with `websocket.receive_json()` and validates
 * it as a `ChatRequest`, so the two shapes are identical by construction.
 */
export type ChatStreamClientMessage = ChatRequest;

/**
 * Server -> client frame on `WS /chat/stream`.
 *
 * The backend replies with `websocket.send_text()` only, so every frame is a
 * bare string rather than a JSON envelope. In RAG mode a retrieved-source
 * preview and a separator arrive first, then the answer arrives roughly one
 * token per frame. There is no frame type tag and no end-of-stream marker: the
 * client concatenates frames and decides for itself when the stream went quiet.
 */
export type ChatStreamServerMessage = string;
