/**
 * Generated by `backend/schemas/typescript.py` -- DO NOT EDIT BY HAND.
 *
 * The Pydantic models under `backend/schemas/` are the single source of truth
 * for every payload crossing the frontend/backend boundary. Regenerate with:
 *
 *     make generate_api_types
 *
 * `tests/api/test_api_contract.py` fails the build when this file is stale.
 */

/** Body of `POST /chat/`, and the client -> server frame of `WS /chat/stream`. */
export interface ChatRequest {
  text: string;
  conversation_id: string;
  rag?: boolean;
}

/** One persisted question/answer exchange. */
export interface ChatMessageInfo {
  id: number;
  question: string;
  answer: string;
  created_at: string;
}

/** Response of `GET /chat/history/{conversation_id}`. */
export interface ChatHistoryResponse {
  conversation_id: string;
  messages: ChatMessageInfo[];
}

/** One entry in the `GET /documents` listing. */
export interface DocumentInfo {
  document_id: string;
  filename: string;
  size: number;
  content_type: string;
  version_hash: string;
}

/** Response of `POST /documents`. */
export interface DocumentUploadResponse {
  document_id: string;
  filename: string;
}

/** Response of `GET /documents`. */
export interface DocumentListResponse {
  documents: DocumentInfo[];
}

/** Response of `GET /health`. */
export interface HealthResponse {
  status: string;
  version: string;
}

/** Retrieved-chunk preview. Sent once, in RAG mode only, before the answer. */
export interface SourcesFrame {
  type: "sources";
  text: string;
}

/** One piece of the answer. Concatenate these in arrival order. */
export interface TokenFrame {
  type: "token";
  text: string;
}

/** Generation failed. No further token frames belong to this response. */
export interface ErrorFrame {
  type: "error";
  message: string;
}

/** End of the response. Always the last frame, on success and on failure. */
export interface DoneFrame {
  type: "done";
}

/**
 * Client -> server frame on `WS /chat/stream`.
 *
 * The endpoint reads each frame with `websocket.receive_json()` and validates
 * it as a `ChatRequest`, so the two shapes are identical by construction.
 */
export type ChatStreamClientMessage = ChatRequest;

/**
 * Server -> client frame on `WS /chat/stream`.
 *
 * Discriminated on `type`. Exactly one terminal frame ends every response --
 * `done` on success, `error` followed by `done` on failure -- so a client stops
 * reading at `done` and never has to infer the end of a stream from a pause.
 */
export type ChatStreamServerMessage = SourcesFrame | TokenFrame | ErrorFrame | DoneFrame;
