"""
Render the API payload schemas as a TypeScript declaration file.

The Pydantic models in this package are the single source of truth for every
payload that crosses the frontend/backend boundary. This module turns them into
``frontend/src/types/api.ts`` so the two sides cannot drift apart silently.

After changing any exported model, run::

    make generate_api_types

``tests/api/test_api_contract.py`` fails the build when the generated file is
stale, so a forgotten regeneration is caught in CI rather than at runtime.
"""

from __future__ import annotations

import json
import types
import typing
from pathlib import Path

from pydantic import BaseModel

from schemas.chat import ChatHistoryResponse, ChatMessageInfo, ChatRequest
from schemas.documents import DocumentInfo, DocumentListResponse, DocumentUploadResponse
from schemas.health import HealthResponse
from schemas.ws import DoneFrame, ErrorFrame, SourcesFrame, TokenFrame

ROOT_PATH = Path(__file__).parents[2]
TYPESCRIPT_PATH = ROOT_PATH / "frontend" / "src" / "types" / "api.ts"

# Every model the frontend is allowed to see. A model referenced by an exported
# model but missing from this tuple is a hard error rather than a silent `any`.
# The frames the server can push down `WS /chat/stream`, in the order they are
# rendered into the discriminated union.
WS_SERVER_FRAMES: tuple[type[BaseModel], ...] = (SourcesFrame, TokenFrame, ErrorFrame, DoneFrame)

EXPORTED_MODELS: tuple[type[BaseModel], ...] = (
    ChatRequest,
    ChatMessageInfo,
    ChatHistoryResponse,
    DocumentInfo,
    DocumentUploadResponse,
    DocumentListResponse,
    HealthResponse,
    *WS_SERVER_FRAMES,
)

# Request bodies may omit any field that has a default, so those fields become
# optional in TypeScript. Response bodies are always fully serialised by
# Pydantic, so every field stays required no matter what its default is.
REQUEST_MODELS: frozenset[type[BaseModel]] = frozenset({ChatRequest})

MODEL_NOTES: dict[type[BaseModel], str] = {
    ChatRequest: "Body of `POST /chat/`, and the client -> server frame of `WS /chat/stream`.",
    ChatMessageInfo: "One persisted question/answer exchange.",
    ChatHistoryResponse: "Response of `GET /chat/history/{conversation_id}`.",
    DocumentInfo: "One entry in the `GET /documents` listing.",
    DocumentUploadResponse: "Response of `POST /documents`.",
    DocumentListResponse: "Response of `GET /documents`.",
    HealthResponse: "Response of `GET /health`.",
    SourcesFrame: "Retrieved-chunk preview. Sent once, in RAG mode only, before the answer.",
    TokenFrame: "One piece of the answer. Concatenate these in arrival order.",
    ErrorFrame: "Generation failed. No further token frames belong to this response.",
    DoneFrame: "End of the response. Always the last frame, on success and on failure.",
}

PRIMITIVES: dict[type, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
}

HEADER = """\
/**
 * Generated by `backend/schemas/typescript.py` -- DO NOT EDIT BY HAND.
 *
 * The Pydantic models under `backend/schemas/` are the single source of truth
 * for every payload crossing the frontend/backend boundary. Regenerate with:
 *
 *     make generate_api_types
 *
 * `tests/api/test_api_contract.py` fails the build when this file is stale.
 */"""

CLIENT_MESSAGE_ALIAS = """\
/**
 * Client -> server frame on `WS /chat/stream`.
 *
 * The endpoint reads each frame with `websocket.receive_json()` and validates
 * it as a `ChatRequest`, so the two shapes are identical by construction.
 */
export type ChatStreamClientMessage = ChatRequest;"""

SERVER_MESSAGE_DOC = """\
/**
 * Server -> client frame on `WS /chat/stream`.
 *
 * Discriminated on `type`. Exactly one terminal frame ends every response --
 * `done` on success, `error` followed by `done` on failure -- so a client stops
 * reading at `done` and never has to infer the end of a stream from a pause.
 */"""


class UnsupportedAnnotation(TypeError):
    """Raised when a model field uses a type this renderer cannot express."""


def _render_annotation(annotation: object, *, model: type[BaseModel], field: str) -> str:
    """
    Convert a single Python annotation into its TypeScript equivalent.

    Args:
        annotation: The annotation to render, taken from ``model_fields``.
        model: The model the field belongs to, used for error messages.
        field: The field name, used for error messages.

    Returns:
        str: The TypeScript type.

    Raises:
        UnsupportedAnnotation: If the annotation uses a construct this renderer
            does not handle. Failing loudly keeps an unmodelled type from
            silently reaching the frontend as `any`.
    """
    if isinstance(annotation, type) and annotation in PRIMITIVES:
        return PRIMITIVES[annotation]

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        if annotation not in EXPORTED_MODELS:
            raise UnsupportedAnnotation(
                f"{model.__name__}.{field} refers to {annotation.__name__}, which is not listed in EXPORTED_MODELS."
            )
        return annotation.__name__

    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if origin is typing.Literal:
        # json.dumps renders each value as its TypeScript literal: "token", 3, true.
        return " | ".join(json.dumps(arg) for arg in args)

    if origin is list:
        (item,) = args
        return f"{_render_annotation(item, model=model, field=field)}[]"

    if origin in (typing.Union, types.UnionType):
        rendered = ["null" if arg is type(None) else _render_annotation(arg, model=model, field=field) for arg in args]
        # dict.fromkeys de-duplicates while preserving declaration order.
        return " | ".join(dict.fromkeys(rendered))

    raise UnsupportedAnnotation(
        f"{model.__name__}.{field} has type {annotation!r}, which cannot be rendered. "
        f"Extend _render_annotation() in {__name__} to support it."
    )


def _render_model(model: type[BaseModel]) -> str:
    """
    Render a single Pydantic model as a TypeScript interface.

    Args:
        model: The model to render. It must have an entry in ``MODEL_NOTES``.

    Returns:
        str: The interface declaration, without a trailing newline.
    """
    allows_omitted_fields = model in REQUEST_MODELS

    lines = [f"/** {MODEL_NOTES[model]} */", f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        rendered = _render_annotation(field.annotation, model=model, field=name)
        separator = "?:" if allows_omitted_fields and not field.is_required() else ":"
        lines.append(f"  {name}{separator} {rendered};")
    lines.append("}")

    return "\n".join(lines)


def _render_ws_server_union() -> str:
    """
    Render the discriminated union of every server -> client WebSocket frame.

    Returns:
        str: The documented type alias, without a trailing newline.
    """
    members = " | ".join(frame.__name__ for frame in WS_SERVER_FRAMES)
    return f"{SERVER_MESSAGE_DOC}\nexport type ChatStreamServerMessage = {members};"


def render_typescript() -> str:
    """
    Render the complete contract file.

    Returns:
        str: The full contents of ``frontend/src/types/api.ts``.
    """
    blocks = [
        HEADER,
        *(_render_model(model) for model in EXPORTED_MODELS),
        CLIENT_MESSAGE_ALIAS,
        _render_ws_server_union(),
    ]
    return "\n\n".join(blocks) + "\n"


def write_typescript() -> Path:
    """
    Render the contract and write it into the frontend source tree.

    Newlines are forced to LF so the file is byte-identical regardless of the
    platform it was generated on; the staleness test compares exact bytes.

    Returns:
        Path: The path that was written.
    """
    TYPESCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPESCRIPT_PATH.write_text(render_typescript(), encoding="utf-8", newline="\n")
    return TYPESCRIPT_PATH
