"""
Render the API payload schemas as a TypeScript declaration file.

The Pydantic models in this package are the single source of truth for every
payload that crosses the frontend/backend boundary. This module turns them into
``frontend/src/types/api.ts`` so the two sides cannot drift apart silently.

After changing any exported model, run::

    make generate_api_types

``tests/api/test_api_contract.py`` fails the build when the generated file is
stale, so a forgotten regeneration is caught in CI rather than at runtime.
"""

from __future__ import annotations

import types
import typing
from pathlib import Path

from pydantic import BaseModel

from schemas.chat import ChatRequest
from schemas.documents import DocumentInfo, DocumentListResponse, DocumentUploadResponse
from schemas.health import HealthResponse

ROOT_PATH = Path(__file__).parents[2]
TYPESCRIPT_PATH = ROOT_PATH / "frontend" / "src" / "types" / "api.ts"

# Every model the frontend is allowed to see. A model referenced by an exported
# model but missing from this tuple is a hard error rather than a silent `any`.
EXPORTED_MODELS: tuple[type[BaseModel], ...] = (
    ChatRequest,
    DocumentInfo,
    DocumentUploadResponse,
    DocumentListResponse,
    HealthResponse,
)

# Request bodies may omit any field that has a default, so those fields become
# optional in TypeScript. Response bodies are always fully serialised by
# Pydantic, so every field stays required no matter what its default is.
REQUEST_MODELS: frozenset[type[BaseModel]] = frozenset({ChatRequest})

MODEL_NOTES: dict[type[BaseModel], str] = {
    ChatRequest: "Body of `POST /chat/`, and the client -> server frame of `WS /chat/stream`.",
    DocumentInfo: "One entry in the `GET /documents` listing.",
    DocumentUploadResponse: "Response of `POST /documents`.",
    DocumentListResponse: "Response of `GET /documents`.",
    HealthResponse: "Response of `GET /health`.",
}

PRIMITIVES: dict[type, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
}

HEADER = """\
/* eslint-disable sonarjs/redundant-type-aliases -- `ChatStreamServerMessage`
   aliases `string` deliberately: naming the wire frame makes call sites read as
   protocol code, and gives the type somewhere to live if the backend ever moves
   to structured frames. */

/**
 * Generated by `backend/schemas/typescript.py` -- DO NOT EDIT BY HAND.
 *
 * The Pydantic models under `backend/schemas/` are the single source of truth
 * for every payload crossing the frontend/backend boundary. Regenerate with:
 *
 *     make generate_api_types
 *
 * `tests/api/test_api_contract.py` fails the build when this file is stale.
 */"""

WEBSOCKET_CONTRACT = """\
/**
 * Client -> server frame on `WS /chat/stream`.
 *
 * The endpoint reads each frame with `websocket.receive_json()` and validates
 * it as a `ChatRequest`, so the two shapes are identical by construction.
 */
export type ChatStreamClientMessage = ChatRequest;

/**
 * Server -> client frame on `WS /chat/stream`.
 *
 * The backend replies with `websocket.send_text()` only, so every frame is a
 * bare string rather than a JSON envelope. In RAG mode a retrieved-source
 * preview and a separator arrive first, then the answer arrives roughly one
 * token per frame. There is no frame type tag and no end-of-stream marker: the
 * client concatenates frames and decides for itself when the stream went quiet.
 */
export type ChatStreamServerMessage = string;"""


class UnsupportedAnnotation(TypeError):
    """Raised when a model field uses a type this renderer cannot express."""


def _render_annotation(annotation: object, *, model: type[BaseModel], field: str) -> str:
    """
    Convert a single Python annotation into its TypeScript equivalent.

    Args:
        annotation: The annotation to render, taken from ``model_fields``.
        model: The model the field belongs to, used for error messages.
        field: The field name, used for error messages.

    Returns:
        str: The TypeScript type.

    Raises:
        UnsupportedAnnotation: If the annotation uses a construct this renderer
            does not handle. Failing loudly keeps an unmodelled type from
            silently reaching the frontend as `any`.
    """
    if isinstance(annotation, type) and annotation in PRIMITIVES:
        return PRIMITIVES[annotation]

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        if annotation not in EXPORTED_MODELS:
            raise UnsupportedAnnotation(
                f"{model.__name__}.{field} refers to {annotation.__name__}, which is not listed in EXPORTED_MODELS."
            )
        return annotation.__name__

    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if origin is list:
        (item,) = args
        return f"{_render_annotation(item, model=model, field=field)}[]"

    if origin in (typing.Union, types.UnionType):
        rendered = ["null" if arg is type(None) else _render_annotation(arg, model=model, field=field) for arg in args]
        # dict.fromkeys de-duplicates while preserving declaration order.
        return " | ".join(dict.fromkeys(rendered))

    raise UnsupportedAnnotation(
        f"{model.__name__}.{field} has type {annotation!r}, which cannot be rendered. "
        f"Extend _render_annotation() in {__name__} to support it."
    )


def _render_model(model: type[BaseModel]) -> str:
    """
    Render a single Pydantic model as a TypeScript interface.

    Args:
        model: The model to render. It must have an entry in ``MODEL_NOTES``.

    Returns:
        str: The interface declaration, without a trailing newline.
    """
    allows_omitted_fields = model in REQUEST_MODELS

    lines = [f"/** {MODEL_NOTES[model]} */", f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        rendered = _render_annotation(field.annotation, model=model, field=name)
        separator = "?:" if allows_omitted_fields and not field.is_required() else ":"
        lines.append(f"  {name}{separator} {rendered};")
    lines.append("}")

    return "\n".join(lines)


def render_typescript() -> str:
    """
    Render the complete contract file.

    Returns:
        str: The full contents of ``frontend/src/types/api.ts``.
    """
    blocks = [HEADER, *(_render_model(model) for model in EXPORTED_MODELS), WEBSOCKET_CONTRACT]
    return "\n\n".join(blocks) + "\n"


def write_typescript() -> Path:
    """
    Render the contract and write it into the frontend source tree.

    Newlines are forced to LF so the file is byte-identical regardless of the
    platform it was generated on; the staleness test compares exact bytes.

    Returns:
        Path: The path that was written.
    """
    TYPESCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPESCRIPT_PATH.write_text(render_typescript(), encoding="utf-8", newline="\n")
    return TYPESCRIPT_PATH
